"""Rule-based session digest - the floor when no LLM is reachable.

Hooks run without an API key and a subscription machine has none, so a session
whose only summariser is an LLM call is a session that silently disappears.
This produces a small, deterministic record from the turns alone: what was
asked first and last, how much happened, and which files were touched. An LLM
summary is strictly better and replaces this when one is configured.
"""

import re

MAX_PROMPT_CHARS = 300
MAX_FILES = 12

# A path with a directory and an extension. Deliberately narrow: bare words and
# extensionless names produce far more noise than the list is worth.
_FILE_RE = re.compile(r"(?<![\w/.])[\w.-]+(?:/[\w.-]+)+\.[A-Za-z0-9]{1,6}(?![\w/])")

# Skill bodies, reminders and command output all reach the transcript with
# role=user. Reporting them as the user's prompt makes the record lie about
# what was asked, so they are excluded from prompt selection (but still count
# as turns and still contribute file mentions).
_INJECTED_PREFIXES = (
    "<system-reminder",
    "<local-command",
    "<command-",
    "Base directory for this skill:",
    "Caveat: The messages below were generated by the user",
)


def _is_injected(text: str) -> bool:
    return text.lstrip().startswith(_INJECTED_PREFIXES)


def _clip(text: str) -> str:
    text = " ".join(text.split())
    return text if len(text) <= MAX_PROMPT_CHARS else text[:MAX_PROMPT_CHARS] + "..."


def digest_turns(turns: list[dict[str, str]]) -> str:
    if not turns:
        return ""

    prompts = [
        t["content"]
        for t in turns
        if t.get("role") == "user" and not _is_injected(t.get("content", ""))
    ]
    files: list[str] = []
    for turn in turns:
        for match in _FILE_RE.findall(turn.get("content", "")):
            if match not in files:
                files.append(match)

    lines = [f"Session digest ({len(turns)} turns, no LLM summariser available)"]
    if prompts:
        lines.append(f"- opened with: {_clip(prompts[0])}")
        if len(prompts) > 1:
            lines.append(f"- last asked: {_clip(prompts[-1])}")
    if files:
        shown = files[:MAX_FILES]
        suffix = f" (+{len(files) - len(shown)} more)" if len(files) > len(shown) else ""
        lines.append(f"- files touched: {', '.join(shown)}{suffix}")
    return "\n".join(lines)
