"""A session must survive with no LLM reachable: hooks run without an API key,
and a subscription machine has none at all. The digest is the floor - never the
ceiling - so an LLM summary still replaces it when one is configured."""

from axon.memory.digest import digest_turns

TURNS = [
    {"role": "user", "content": "why does the session hook never fire?"},
    {"role": "assistant", "content": "Checked src/axon/cli/pb.py and ran pytest tests/memory"},
    {"role": "user", "content": "fix the parser then"},
    {"role": "assistant", "content": "Edited src/axon/memory/transcript.py"},
]


def test_digest_keeps_the_first_and_last_user_prompt():
    text = digest_turns(TURNS)

    assert "why does the session hook never fire?" in text
    assert "fix the parser then" in text


def test_digest_reports_the_turn_count():
    assert "4 turns" in digest_turns(TURNS)


def test_digest_lists_the_files_touched():
    text = digest_turns(TURNS)

    assert "src/axon/cli/pb.py" in text
    assert "src/axon/memory/transcript.py" in text


def test_digest_of_no_turns_is_empty_not_a_crash():
    assert digest_turns([]) == ""


HARNESS_NOISE = [
    {"role": "user", "content": "<system-reminder>\nsome injected context\n</system-reminder>"},
    {"role": "user", "content": "Base directory for this skill: /x/y\n# Diagnose\nA discipline..."},
    {"role": "user", "content": "<local-command-stdout>ok</local-command-stdout>"},
    {"role": "user", "content": "Caveat: The messages below were generated by the user while..."},
    {"role": "user", "content": "the real question I actually typed"},
    {"role": "assistant", "content": "answered"},
]


def test_digest_ignores_harness_injected_turns_when_picking_prompts():
    """Skill bodies, system reminders and local-command output all arrive with
    role=user. Reporting them as what the user asked makes the record lie."""
    text = digest_turns(HARNESS_NOISE)

    assert "opened with: the real question I actually typed" in text
    assert "system-reminder" not in text
    assert "Base directory for this skill" not in text
